### ISSUE TITLE
Redshift support 

### ISSUE THREAD

**Issue by marcin-maslowski-jt** [rudderlabs/dbt-id-stitching#5]
Hi! 
Does this package work on Redshift? 

Thank You!

**Comment by esadek** [comment]
Hi @marcin-maslowski-jt,
Yes, this package works with Amazon Redshift. You should just need to change `information_schema` to `SVV_COLUMNS`. `information_schema` is referenced in [models/schema.yml](https://github.com/rudderlabs/dbt-id-stitching/blob/main/models/schema.yml#L4) and [models/queries.sql](https://github.com/rudderlabs/dbt-id-stitching/blob/main/models/queries.sql#L5).

**Comment by marcin-maslowski-jt** [comment]
@esadek Thank you! Do the other ones work on Redshift also or only on BigQuery? 
![image](https://user-images.githubusercontent.com/107933363/190982648-59b00086-3ca9-44ee-bfb7-27374d3427b2.png)

**Comment by bwalvoord** [comment]
The rest of the models should work without any other modifications.

**Comment by bwalvoord** [comment]
Yes.  In the queries model, you can just hardcode svv_columns instead of
the information_schema.columns and you should be good to go.
