### ISSUE TITLE
dropped table is still referenced by dbt run --full-refresh --select queries edges

### ISSUE THREAD

**Issue by csjasonk** [rudderlabs/dbt-id-stitching#9]
this is for a Snowflake db. I had a table called software_payment 

I had already run dep deps, and dbt run --full-refresh --select queries edges and everything ran successfully in DBT.

In Snowflake, I renamed the table software_payment to customer_payments

Since renaming the table, if I run the command  dbt run --full-refresh --select queries edges, the edges fails to run with the following error:

Failure during expansion of view 'EMAIL_TO_ANONYMOUS_ID_RUDDER_ID': SQL compilation error:
  Object 'DATABASE.SCHEMA.SOFTWARE_PAYMENT' does not exist or not authorized.
  
...where database.schema is my actual database and actual schema. 

Oddly:

if I run dbt build --select queries edges the queries and edges both build successfully.

If I run dbt run --select queries edges that works successfully

I tried adding an exclusion for this table in the dbt_project.yml and this did successfully add it to the Queries view in Snowflake.

Further, I looked through the information_schema table, and confirmed software_payment is not found anywhere.

Further, in the error returned, I can see that the customer_payments is in the queries that ran before the run failed for not finding the software_payment table.

Shouldn't setting the --full-refresh force things to recheck the information_schema? And/also the dbt_project.yml to suppress that table? 

Note I tried things with and without tables-to-exclude: ('software_payment') in the dbt_project.yml and the error doesn't change...

Failure during expansion of view 'EMAIL_TO_ANONYMOUS_ID_RUDDER_ID': SQL compilation error:
  Object 'DATABASE.SCHEMA.SOFTWARE_PAYMENT' does not exist or not authorized.
  

  
I'll probably add a fake software_payment table in so it can just run but perhaps this indicates something else is not running as it should be?

Where could the query be getting the software_payment if it's not in the information_schema anywhere? So. Strange.

**Comment by bwalvoord** [comment]
It's interesting that is says "expansion of view" as this must be in either queries or check_edges.  If you look at the definition of both of those in snowflake do either still reference that table?  It would be fine to drop those directly in snowflake.

**Comment by csjasonk** [comment]
ah.. I see the actual  EMAIL_TO_ANONYMOUS_ID_RUDDER_ID view has the reference. I take it these views all get created when things are first setup/run through DBT.. so there isn't anything that would go back and erase the view.

**Comment by csjasonk** [comment]
Actually, I found the changes for the queries.sql that allow it to run in BQ:

Google has a weird thing around escaping escape characters, using double quotes instead of 3 single quotes allows this line to run:

SELECT "SELECT DISTINCT " || a.cn || "::TEXT AS edge_a, '" || a.cn || "' AS edge_a_label, " || b.cn || "::TEXT AS edge_b, '" || b.cn || "' AS edge_b_label FROM " || a.tn || " WHERE COALESCE(" || a.cn || "::TEXT, '') != '' AND COALESCE(" || b.cn || "::TEXT, '') != ''" AS sql_to_run

the other thing that is different in BQ is how it labels the information schema. 

This is the compiled SQL that ran successfully where my_dataset is the actual data set name inside the project. Note the INFORMATION_SCHEMA.COLUMNS must be in all caps, otherwise it throws a project name not recognized error.

`WITH columns AS (
    SELECT
        column_name AS cn,
        table_catalog || '.' || table_schema || '.' || table_name AS tn
    FROM my_data_set.INFORMATION_SCHEMA.COLUMNS
    WHERE
        LOWER(column_name) IN ('anonymous_id', 'user_id', 'email', 'context_traits_email', 'identity')
        
        
        
        
        AND NOT LOWER(table_name) LIKE 'snapshot_%'
        AND NOT LOWER(table_name) LIKE 'sync_data_%'
        AND NOT LOWER(table_name) LIKE 'failed_records_%'
)

SELECT "SELECT DISTINCT " || a.cn || "::TEXT AS edge_a, '" || a.cn || "' AS edge_a_label, " || b.cn || "::TEXT AS edge_b, '" || b.cn || "' AS edge_b_label FROM " || a.tn || " WHERE COALESCE(" || a.cn || "::TEXT, '') != '' AND COALESCE(" || b.cn || "::TEXT, '') != ''" AS sql_to_run
FROM columns AS a
INNER JOIN columns AS b
    ON a.tn = b.tn
        AND a.cn > b.cn`
